#cloud-config

coreos:
    oem:
      id: hetzner
      name: Hetzner Barebone Servers
      version-id: 0.0.1
      home-url: http://www.hetzner.de
      bug-report-url: https://github.com/coreos/coreos-overlay
write_files:
    - path: /run/systemd/system/etcd.service.d/10-oem.conf
      permissions: 0644
      content: |
        [Service]
        Environment=ETCD_PEER_ELECTION_TIMEOUT=1200
